window.PICKUP_LINES = [
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Do you have a map? I keep getting lost in your eyes.",
    "Even Google can’t find someone better than you.",
    "Are you French? Because Eiffel for you.",
    "You’re the reason even stars get jealous.",
    "My heart wasn’t broken, but you still managed to fix it.",
    "I wasn’t planning to fall in love… but then you smiled.",
    "You must be a magician, because every time I look at you, everyone else disappears.",
    "Are you Wi-Fi? Because I’m feeling a real connection.",
    "I would never play hide & seek with you, because someone like you is impossible to find.",
    "Even my morning coffee doesn’t wake me up like you do.",
    "If beauty were time, you’d be eternity.",
    "I don’t need the stars in the sky… I just need the sparkle in your eyes.",
    "Do you believe in love at first sight, or should I walk by again?",
    "You’re not just a dream girl—you’re my entire dream world.",
    "If kisses were snowflakes, I’d send you a blizzard.",
    "My heart skips a beat every time I see your name on my screen.",
    "Even the sun is jealous of the way you shine.",
    "If I had a flower for every time I thought of you, I could walk in my garden forever.",
    "You make my heart do backflips like an Olympic gymnast.",
    "Are you made of sugar? Because you’re the sweetest thing in my life.",
    "I don’t need a shooting star to make a wish—you’re already here."
  ];
